#pragma once
#include <iostream>
#include <chrono>
#include <vector>
#include <random>
#include <string>
#include <unordered_map>
#include <exception>
#include <fstream>
#include <stack>
#include <iterator>
#include <stdio.h>
#include <ctype.h>
#include <sstream>
#include <cstdarg>
#include <algorithm>
#include <time.h>
#include <map>